import type { CashTransaction, DocumentRow, Product, ThirdParty } from "@/lib/types";

export const thirdParties: ThirdParty[] = [
  {
    id: "atlas-market",
    type: "customer",
    name: "Atlas Market SARL",
    commercialName: "Atlas Market",
    ice: "001982736000089",
    city: "Casablanca",
    email: "finance@atlas-market.ma",
    phone: "+212 522 31 44 20",
    balance: 86400,
    status: "active",
  },
  {
    id: "nova-industries",
    type: "both",
    name: "Nova Industries Maroc",
    commercialName: "Nova Industries",
    ice: "002149875000032",
    city: "Tanger",
    email: "achats@nova-industries.ma",
    phone: "+212 539 61 12 88",
    balance: 24150,
    status: "active",
  },
  {
    id: "sud-logistique",
    type: "supplier",
    name: "Sud Logistique SA",
    commercialName: "Sud Logistique",
    ice: "001667490000071",
    city: "Marrakech",
    email: "contact@sudlogistique.ma",
    phone: "+212 524 38 10 90",
    balance: -39200,
    status: "active",
  },
  {
    id: "med-print",
    type: "supplier",
    name: "Med Print Services",
    commercialName: "Med Print",
    ice: "002753918000014",
    city: "Rabat",
    email: "facturation@medprint.ma",
    phone: "+212 537 70 45 11",
    balance: -7800,
    status: "active",
  },
];

export const products: Product[] = [
  {
    id: "prd-001",
    type: "product",
    sku: "PC-LEN-14",
    name: "PC portable Lenovo 14 pouces",
    category: "Matériel informatique",
    unit: "Unité",
    salePrice: 7200,
    purchasePrice: 5950,
    taxRate: 20,
    stock: 9,
    minStock: 5,
    status: "active",
  },
  {
    id: "prd-002",
    type: "product",
    sku: "TON-HP-85A",
    name: "Toner HP 85A compatible",
    category: "Consommables",
    unit: "Unité",
    salePrice: 240,
    purchasePrice: 165,
    taxRate: 20,
    stock: 3,
    minStock: 8,
    status: "active",
  },
  {
    id: "srv-001",
    type: "service",
    sku: "SRV-MAINT",
    name: "Maintenance mensuelle parc informatique",
    category: "Services",
    unit: "Mois",
    salePrice: 3500,
    purchasePrice: 0,
    taxRate: 20,
    stock: 0,
    minStock: 0,
    status: "active",
  },
];

export const quotes: DocumentRow[] = [
  {
    id: "q-001",
    number: "DEV-2026-0001",
    customer: "Atlas Market SARL",
    documentDate: "2026-05-02",
    status: "sent",
    total: 41400,
  },
  {
    id: "q-002",
    number: "DEV-2026-0002",
    customer: "Nova Industries Maroc",
    documentDate: "2026-05-06",
    status: "accepted",
    total: 18600,
  },
];

export const invoices: DocumentRow[] = [
  {
    id: "f-001",
    number: "FAC-2026-0001",
    customer: "Atlas Market SARL",
    documentDate: "2026-04-15",
    dueDate: "2026-05-15",
    status: "partially_paid",
    total: 122400,
    paid: 36000,
  },
  {
    id: "f-002",
    number: "FAC-2026-0002",
    customer: "Nova Industries Maroc",
    documentDate: "2026-03-25",
    dueDate: "2026-04-24",
    status: "overdue",
    total: 24150,
    paid: 0,
  },
  {
    id: "f-003",
    number: "FAC-2026-0003",
    customer: "Atlas Market SARL",
    documentDate: "2026-05-04",
    dueDate: "2026-06-03",
    status: "sent",
    total: 31200,
    paid: 0,
  },
];

export const cashTransactions: CashTransaction[] = [
  {
    id: "ct-001",
    account: "Banque CIH",
    label: "Encaissement FAC-2026-0001",
    date: "2026-05-05",
    type: "in",
    amount: 36000,
  },
  {
    id: "ct-002",
    account: "Banque CIH",
    label: "Paiement fournisseur Sud Logistique",
    date: "2026-05-03",
    type: "out",
    amount: 12400,
  },
  {
    id: "ct-003",
    account: "Caisse principale",
    label: "Achat fournitures bureau",
    date: "2026-05-01",
    type: "out",
    amount: 980,
  },
];

export const dashboard = {
  revenue: invoices.reduce((sum, invoice) => sum + invoice.total, 0),
  collected: invoices.reduce((sum, invoice) => sum + (invoice.paid ?? 0), 0),
  overdueInvoices: invoices.filter((invoice) => invoice.status === "overdue").length,
  supplierDebt: 47000,
  cashBalance: 184620,
  grossMargin: 28.4,
  lowStock: products.filter((product) => product.type === "product" && product.stock <= product.minStock).length,
};
